name: Lint Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v2

      - name: Node.js einrichten
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Linter ausführen
        run: npx eslint .
